version: '3'
services:
  net_app:
    image: my_net_app
    logging:
      driver: "fluentd"
      options:
        tag: netapp

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300

  splunk:
    build: "splunk"
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_USER: "root"
      SPLUNK_PASSWORD: "Password1!"
    ports:
      - "8000:8000"
      - "8088:8088" # http event collector

  fluentd:
    image: marsikop/efs_fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./logs:/logs
    environment:
      - FLUENTD_CONF=fluent.conf
    ports:
      - 8081:8080
      - 24224:24224

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601